// client/src/components/Graph.vue
<template>
  <!-- <q-card class="my-card bg-white text-white"> -->
  <q-card class="rounded graph-container bg-primary text-secondary">
    <q-card-section class="graph-card">
      <!-- {{dataArray}} -->
      <!-- {{ temperatureData }} -->
      <apexchart
        class="graph-graph"
        width="100%"
        ref="chart"
        :options="chartOptions"
        :series="series"
      ></apexchart>
    </q-card-section>
  </q-card>
</template>

<script>
import VueApexCharts from "vue3-apexcharts";
import "../styles/customCSS.css";

export default {
  name: "LineExample",
  components: {
    apexchart: VueApexCharts,
  },
  props: ["chartHeight", "dataArray", "settings", "targetTemperature"],
  data: function () {
    return {
      temperatureData: [],
      targetData: [],
      labelColor: "592D1D",
      intervalid1: null,
      chartOptions: {
        chart: {
          id: "realtime",
          type: "line",
          grid: {
            show: false, // you can either change hear to disable all grids

            yaxis: {
              lines: {
                show: false, //or just here to disable only y axis
              },
            },
          },
          redrawOnWindowResize: true,
          animations: {
            enabled: true,
            easing: "linear",
            dynamicAnimation: {
              speed: 500,
            },
            animateGradually: {
              enabled: true,
              delay: 2,
            },
          },
          toolbar: {
            show: false,
          },
          zoom: {
            enabled: false,
          },
        },
        grid: {
          show: false,
          xaxis: {
            lines: {
              show: false,
            },
          },
          yaxis: {
            lines: {
              show: false,
            },
          },
        },
        colors: [
          this.settings.VUE_COLOUR.accent,
          this.settings.VUE_COLOUR.info,
        ],
        dataLabels: {
          enabled: false,
        },
        stroke: {
          curve: "smooth",
          lineCap: 'butt',
          width: [2, 5],
          dashArray: [0, 0],
        },
        title: {
          align: "left",
        },
        markers: {
          size: 0,
        },
        tooltip: {
          enabled: false,
          followCursor: false,
          fillSeriesColor: true,
          x: {
            show: false,
          },
        },
        xaxis: {
          type: "datetime",
          tickAmount: 3,
          range: 30000,
          labels: {
            style: {
              colors: this.settings.VUE_COLOUR.secondary,
            },
            formatter: function (timestamp) {
              var currentDate = new Date();

              // var date = new Date(timestamp);
              // var label =
              //   date.getHours() +
              //   ":" +
              //   date.getMinutes() +
              //   ":" +
              //   ("0" + date.getSeconds()).slice(-2);

              var label = "";

              if (timestamp >= currentDate.getTime() - 31000) {
                label = "T-30";
              }

              if (timestamp >= currentDate.getTime() - 21000) {
                label = "T-20";
              }

              if (timestamp >= currentDate.getTime() - 11000) {
                label = "T-10";
              }

              if (timestamp >= currentDate.getTime() - 1000) {
                label = "Now";
              }

              return label;
            },
            // rotateAlways: true,
          },
          axisBorder: {
            show: true,
            color: this.settings.VUE_COLOUR.info,
            offsetX: -4,
            offsetY: 0,
          },
          axisTicks: {
            show: true,
            color: this.settings.VUE_COLOUR.info,
          },
        },
        yaxis: {
          labels: {
            offsetX: -5,
            style: {
              colors: this.settings.VUE_COLOUR.secondary,
            },
          },
          title: {
            text: "TEMPERATURE (°C)",
            rotate: -90,
            offsetX: 0,
            offsetY: 0,
            style: {
              color: this.settings.VUE_COLOUR.secondary,
              fontSize: "12px",
              fontFamily: "customfont2",
              fontWeight: 600,
            },
          },
          axisBorder: {
            show: true,
            color: this.settings.VUE_COLOUR.info,
            offsetX: 0,
            offsetY: 0,
          },
        },
        legend: {
          show: false,
        },
      },
      series: [
        {
          name: "Temperature",
          data: this.dataArray,
        },
        {
          name: "Target",
          data: this.targetTemperature,
        },
      ],
    };
  },
  mounted() {
    this.updateChart();
  },
  watch: {
    chartHeight: function () {
      this.resize();
    },
  },
  methods: {
    // Method to resize chart on window resize
    resize() {
      setTimeout(
        () =>
          (this.chartOptions = {
            chart: {
              height: "100%",
            },
          }),
        3000
      );
    },
    initChart: function () {
      this.temperatureData = this.dataArray;

      var backInTime = new Date(this.dataArray[this.dataArray.length - 1].x)
      backInTime = backInTime - 60000
      this.targetData.push({
        x: backInTime,
        y: this.targetTemperature,
      });

      this.targetData.push({
        x: this.dataArray[this.dataArray.length - 1].x,
        y: this.targetTemperature,
      });
    },
    updateChart: function () {
      var me = this;
      this.intervalid1 = setInterval(() => {
        // If the chart data isn't populated (replace with dataArray)
        if (this.temperatureData.length < 25) {
          this.initChart();
        }

        // Replace chart data array (avoid memory leaks)
        if (this.temperatureData.length > 600) {
          this.temperatureData = this.dataArray;
          this.targetData = this.targetData.slice(
            this.targetData.length - 60,
            this.targetData.length
          );
        }

        // Add chart temperature data
        let newTemperature = {
          x: this.dataArray[this.dataArray.length - 1].x,
          y: this.dataArray[this.dataArray.length - 1].y,
        };
        this.temperatureData.push(newTemperature);

        // Add chart target data
        let newTarget = {
          x: this.dataArray[this.dataArray.length - 1].x,
          y: this.targetTemperature,
        };
        this.targetData.push(newTarget);

        // Update chart
        me.$refs.chart.updateSeries([
          {
            name: "Temperature",
            data: this.temperatureData,
          },
          {
            name: "Target",
            data: this.targetData,
          },
        ]);
      }, 500);
    },
  },
};
</script>

// client-react/src/components/Graph.js
import React, { Component, useState, useEffect } from "react";
import Chart from "react-apexcharts";
import Paper from "@mui/material/Paper";

class Graph extends Component {
  constructor(props) {
    super(props);
    this.state = {
      options: {
        chart: {
          id: "realtime",
          grid: {
            show: false, // you can either change hear to disable all grids

            yaxis: {
              lines: {
                show: false, //or just here to disable only y axis
              },
            },
          },
        },
      },
      series: [
        {
          name: "series-1",
          data: [30, 40, 45, 50, 49, 60, 70, 91],
        },
        {
          name: "DATA",
          data: 30,
        },
      ],
    };
  }

  render() {
    const temperatureData = [];
    const targetData = [];

    const initChart = () => {
      temperatureData = this.props.dataArray;

      const currentTime = Date(
        this.props.dataArray[this.props.dataArray.length - 1].x
      );

      const backInTime = currentTime - 60000;
      for (var i = backInTime; i <= currentTime; i += 1000) {
        targetData.push({
          x: new Date(i),
          y: this.props.targetTemperature,
        });
      }

      targetData.push({
        x: this.props.dataArray[this.props.dataArray.length - 1].x,
        y: this.targetTemperature,
      });
    };

    const updateChart = () => {
      alert("update");

      const interval = setInterval(() => {
        // If the chart data isn't populated (replace with dataArray)
        if (temperatureData.length < 25) {
          initChart();
        }

        // Replace chart data array (avoid memory leaks)
        if (temperatureData.length > 600) {
          temperatureData = this.props.dataArray;
          targetData = targetData.slice(
            targetData.length - 60,
            targetData.length
          );
        }
        // Add chart temperature data
        let newTemperature = {
          x: this.props.dataArray[this.props.dataArray.length - 1].x,
          y: this.props.dataArray[this.props.dataArray.length - 1].y,
        };
        temperatureData.push(newTemperature);

        // Add chart target data
        let newTarget = {
          x: this.props.dataArray[this.props.dataArray.length - 1].x,
          y: this.props.targetTemperature,
        };
        targetData.push(newTarget);

        // Update chart
        const newSeries = [];

        this.state.series.map((s) => {
          alert(s.name);

          const data = temperatureData.map((val) => {
            return val.x, val.y;
          });

          newSeries.push({ data, name: s.name });
        });

        newSeries.push();

        this.setState({
          series: newSeries,
        });
      }, 500);
    };

    // const alertData = () => {
    //   const newSeries = [];

    //   this.state.series.map((s) => {
    //     if (s.name == "DATA") {
    //       const data = temperatureData.map((val) => {
    //         return val.x, val.y;
    //       });
    //     } else {
    //       const data = targetData.map((val) => {
    //         return val.x, val.y;
    //       });
    //     }

    //     newSeries.push({ data, name: s.name });
    //   });

    //   newSeries.push();

    //   this.setState({
    //     series: newSeries,
    //   });
    //   //   alert(newSeries);
    // };

    return (
      <Paper elevation={6} className="curve">
        <Chart
          class="graph-graph"
          width="100%"
          ref="chart"
          options={this.state.options}
          series={this.state.series}
        ></Chart>

        <button onClick={updateChart}>Get PID</button>
      </Paper>
    );
  }
}

export default Graph;
